# Generated by Django 3.2.5 on 2021-07-15 15:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='action',
            field=wagtail.core.fields.StreamField([('action', wagtail.core.blocks.StructBlock([('operator', wagtail.core.blocks.CharBlock()), ('type', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
