# Generated by Django 3.2.5 on 2021-07-27 11:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_answer_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpage',
            name='introduction_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
