# Generated by Django 3.2.5 on 2021-07-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('testapp', '0005_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionform',
            name='results_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
