# Generated by Django 3.2.5 on 2021-07-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('testapp', '0006_auto_20210728_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpagerelatedquestions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='questionpagerelatedquestions',
            name='question_ptr',
        ),
        migrations.DeleteModel(
            name='QuestionPage',
        ),
        migrations.DeleteModel(
            name='QuestionPageRelatedQuestions',
        ),
    ]
