# Generated by Django 3.2.5 on 2021-07-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20210728_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='info_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.infobox'),
        ),
    ]
